### ISSUE TITLE
Does not work with of ATTinyCore 1.5.2 / Attiny25, HEX and DEC already reserved

### ISSUE THREAD

**Issue by zexcster** [nerdralph/debugSerial#1]
In file included from ../Library/Arduino15/packages/ATTinyCore/hardware/avr/1.5.2/cores/tiny/Stream.h:26:0,
                 from ../Library/Arduino15/packages/ATTinyCore/hardware/avr/1.5.2/cores/tiny/TinySoftwareSerial.h:5,
                 from ../Library/Arduino15/packages/ATTinyCore/hardware/avr/1.5.2/cores/tiny/Arduino.h:249,
                 from ../sketch/print.ino.cpp:1:
...
...Library/Arduino15/packages/ATTinyCore/hardware/avr/1.5.2/cores/tiny/Print.h:33:13: error: expected unqualified-id before numeric constant #define DEC 10

>> debugSerial.h
108: enum _base {DEC = 10, HEX = 16};
....
had to replace it to
enum _base {DEK = 10, HEKS = 16};
....

**Comment by nerdralph** [comment]
fixed in commit ff3dfd6c0571949a437cc7f9230950a56ec05c57
